// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2

package types

type IdPathReq struct {
	Id string `uri:"id,omitempty"` // uri 标签表示从 URL 路径获取参数
}

type IdResp struct {
	Id string `json:"id,omitempty"` // json 标签表示 JSON 序列化字段名
}

type LoginReq struct {
	Username string `json:"username" binding:"required"` // 用户名
	Password string `json:"password" binding:"required"` // 密码
}

type LoginResp struct {
	Token string `json:"token,omitempty"` // JWT令牌
}

type RegisterReq struct {
	Username string `json:"username" binding:"required"` // 用户名
	Password string `json:"password" binding:"required"` // 密码
}

type RegisterResp struct {
	Message string `json:"message,omitempty"` // 响应消息
}

type UpdateProfileReq struct {
	Name string `json:"name,omitempty"` // 用户名
}

type User struct {
	Id       uint   `json:"id,omitempty"`       // 用户ID
	Name     string `json:"name,omitempty"`     // 用户名
	Password string `json:"password,omitempty"` // 密码
	Status   int    `json:"status,omitempty"`   // 状态：0=正常 1=禁用
	IsAdmin  bool   `json:"isAdmin,omitempty"`  // 是否管理员
}

type UserInfoResp struct {
	Id       uint   `json:"id,omitempty"`
	Username string `json:"username,omitempty"`
	Status   int    `json:"status,omitempty"`
	IsAdmin  bool   `json:"isAdmin,omitempty"`
}
