// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2

package types

type IdPathReq struct {
	Id string `uri:"id,omitempty"` // uri 标签表示从 URL 路径获取参数
}

type IdResp struct {
	Id string `json:"id,omitempty"` // json 标签表示 JSON 序列化字段名
}

type LoginReq struct {
	Name     string `json:"name" binding:"required"`     // 用户名
	Password string `json:"password" binding:"required"` // 密码
}

type LoginResp struct {
	Status       int    `json:"status,omitempty"`       // 状态：1=成功
	Id           uint   `json:"id,omitempty"`           // 用户ID
	Name         string `json:"name,omitempty"`         // 用户名
	Token        string `json:"token,omitempty"`        // JWT令牌
	AccessExpire int64  `json:"accessExpire,omitempty"` // 过期时间
	RefreshAfter int64  `json:"refreshAfter,omitempty"` // 刷新时间
}

type RegisterReq struct {
	Name     string `json:"name" binding:"required"`     // 用户名
	Password string `json:"password" binding:"required"` // 密码
}

type RegisterResp struct {
	Message string `json:"message,omitempty"` // 响应消息
}

type UpdatePasswordReq struct {
	OldPwd string `json:"oldPwd" binding:"required"`       // 旧密码
	NewPwd string `json:"newPwd" binding:"required,min=6"` // 新密码（最少6位）
}

type UpdateProfileReq struct {
	Name string `json:"name,omitempty"` // 用户名
}

type User struct {
	Id       uint   `json:"id,omitempty"`       // 用户ID
	Name     string `json:"name,omitempty"`     // 用户名
	Password string `json:"password,omitempty"` // 密码
	Status   int    `json:"status,omitempty"`   // 状态：0=正常 1=禁用
	IsAdmin  bool   `json:"isAdmin,omitempty"`  // 是否管理员
}

type UserInfoResp struct {
	Id      uint   `json:"id,omitempty"`
	Name    string `json:"name,omitempty"` // 用户名
	Status  int    `json:"status,omitempty"`
	IsAdmin bool   `json:"isAdmin,omitempty"`
}

type UserListReq struct {
	Ids   []string `json:"ids,omitempty"`   // 用户ID列表
	Name  string   `json:"name,omitempty"`  // 用户名模糊搜索
	Page  int      `json:"page,omitempty"`  // 页码
	Count int      `json:"count,omitempty"` // 每页数量
}

type UserListResp struct {
	Count int64  `json:"count"` // 总记录数
	Data  []User `json:"data"`  // 用户列表
}
