// Code generated by goctl. DO NOT EDIT.
package domain

type IdPathReq struct {
	Id string `uri:"id,omitempty"` // uri 标签表示从 URL 路径获取参数
}

type IdResp struct {
	Id string `json:"id,omitempty"` // json 标签表示 JSON 序列化字段名
}

type User struct {
	Id       uint   `json:"id,omitempty"`       // 用户ID
	Name     string `json:"name,omitempty"`     // 用户名
	Password string `json:"password,omitempty"` // 密码
	Status   int    `json:"status,omitempty"`   // 状态：0=正常 1=禁用
	IsAdmin  bool   `json:"isAdmin,omitempty"`  // 是否管理员
	Gender   string `json:"gender,omitempty"`   // 测试todo
}

type RegisterReq struct {
	Name     string `json:"name" binding:"required"`     // 用户名
	Password string `json:"password" binding:"required"` // 密码
}

type RegisterResp struct {
	Message string `json:"message,omitempty"` // 响应消息
}

type LoginReq struct {
	Name     string `json:"name" binding:"required"`     // 用户名
	Password string `json:"password" binding:"required"` // 密码
}

type LoginResp struct {
	Status       int    `json:"status,omitempty"`       // 状态：1=成功
	Id           uint   `json:"id,omitempty"`           // 用户ID
	Name         string `json:"name,omitempty"`         // 用户名
	Token        string `json:"token,omitempty"`        // JWT令牌
	AccessExpire int64  `json:"accessExpire,omitempty"` // 过期时间
	RefreshAfter int64  `json:"refreshAfter,omitempty"` // 刷新时间
}

type UserInfoResp struct {
	Id      uint   `json:"id,omitempty"`
	Name    string `json:"name,omitempty"` // 用户名
	Status  int    `json:"status,omitempty"`
	IsAdmin bool   `json:"isAdmin,omitempty"`
}

type UpdateProfileReq struct {
	Name string `json:"name,omitempty"` // 用户名
}

type UpdatePasswordReq struct {
	OldPwd string `json:"oldPwd" binding:"required"`       // 旧密码
	NewPwd string `json:"newPwd" binding:"required,min=6"` // 新密码（最少6位）
}

type UserListReq struct {
	Ids   []string `json:"ids,omitempty"`   // 用户ID列表
	Name  string   `json:"name,omitempty"`  // 用户名模糊搜索
	Page  int      `json:"page,omitempty"`  // 页码
	Count int      `json:"count,omitempty"` // 每页数量
}

type UserListResp struct {
	Count int64  `json:"count"` // 总记录数
	Data  []User `json:"data"`  // 用户列表
}

type Department struct {
	Id        uint   `json:"id"`
	Name      string `json:"name"`
	LeaderId  uint   `json:"leaderId"`
	ParentId  uint   `json:"parentId"`
	CreatedAt int64  `json:"createdAt"`
}

type DepartmentListReq struct {
	Name string `form:"name,omitempty"`
}

type DepartmentListResp struct {
	List []*Department `json:"list"`
}

type CreateDepartmentReq struct {
	Name     string `json:"name"`
	LeaderId uint   `json:"leaderId,omitempty"`
	ParentId uint   `json:"parentId,omitempty"`
}

type UpdateDepartmentReq struct {
	Id       uint   `json:"id"`
	Name     string `json:"name,omitempty"`
	LeaderId uint   `json:"leaderId,omitempty"`
	ParentId uint   `json:"parentId,omitempty"`
}

type AddDepartmentUserReq struct {
	DepartmentId uint   `json:"departmentId"`
	UserIds      []uint `json:"userIds"`
}

type Todo struct {
	Id          uint          `json:"id"`
	CreatorId   uint          `json:"creatorId"`
	CreatorName string        `json:"creatorName"`
	Title       string        `json:"title"`
	Desc        string        `json:"desc"`
	DeadlineAt  int64         `json:"deadlineAt"`
	Status      int           `json:"status"`
	TodoStatus  int           `json:"todoStatus"`
	Records     []*TodoRecord `json:"records,omitempty"`
	Executors   []*User       `json:"executors,omitempty"`
	CreatedAt   int64         `json:"createdAt"`
}

type TodoRecord struct {
	Id        uint   `json:"id"`
	TodoId    uint   `json:"todoId"`
	UserId    uint   `json:"userId"`
	UserName  string `json:"userName"`
	Content   string `json:"content"`
	Image     string `json:"image"`
	CreatedAt int64  `json:"createdAt"`
}

type CreateTodoReq struct {
	Title       string `json:"title"`
	Desc        string `json:"desc,omitempty"`
	DeadlineAt  int64  `json:"deadlineAt,omitempty"`
	ExecutorIds []uint `json:"executorIds,omitempty"`
}

type UpdateTodoReq struct {
	Id          uint   `json:"id"`
	Title       string `json:"title,omitempty"`
	Desc        string `json:"desc,omitempty"`
	DeadlineAt  int64  `json:"deadlineAt,omitempty"`
	ExecutorIds []uint `json:"executorIds,omitempty"`
}

type TodoListReq struct {
	Page      int   `form:"page,omitempty"`
	Count     int   `form:"count,omitempty"`
	StartTime int64 `form:"startTime,omitempty"`
	EndTime   int64 `form:"endTime,omitempty"`
}

type TodoListResp struct {
	Count int64   `json:"count"`
	List  []*Todo `json:"list"`
}

type FinishTodoReq struct {
	TodoId uint `json:"todoId"`
}

type CreateTodoRecordReq struct {
	TodoId  uint   `json:"todoId"`
	Content string `json:"content,omitempty"`
	Image   string `json:"image,omitempty"`
}
