/**
 * @author: 公众号：IT杨秀才
 * @doc:后端，AI知识进阶，后端面试场景题大全：https://golangstar.cn/
 */
// Code generated by goctl. DO NOT EDIT.
package model

import (
	"context"
	"time"

	"AIWorkHelper/internal/domain"
	"go.mongodb.org/mongo-driver/bson"
	"go.mongodb.org/mongo-driver/bson/primitive"
	"go.mongodb.org/mongo-driver/mongo"
	"go.mongodb.org/mongo-driver/mongo/options"
)

// ApprovalModel 定义了审批数据模型的数据库操作接口
type ApprovalModel interface {
	List(ctx context.Context, req *domain.ApprovalListReq) ([]*Approval, int64, error)
	Insert(ctx context.Context, data *Approval) error
	FindOne(ctx context.Context, id string) (*Approval, error)
	Update(ctx context.Context, data *Approval) error
	Delete(ctx context.Context, id string) error
}

// defaultApprovalModel 是 ApprovalModel 接口的默认实现
type defaultApprovalModel struct {
	col *mongo.Collection // MongoDB 集合对象
}

// NewApprovalModel 创建一个新的 ApprovalModel 实例
func NewApprovalModel(db *mongo.Database) ApprovalModel {
	// 获取名为 "approval" 的集合
	col := db.Collection("approval")
	return &defaultApprovalModel{
		col: col,
	}
}

// List 根据条件查询审批列表
func (m *defaultApprovalModel) List(ctx context.Context, req *domain.ApprovalListReq) ([]*Approval, int64, error) {
	var (
		data []*Approval // 存储查询结果
		opt  = &options.FindOptions{
			// 按创建时间降序排序
			Sort: bson.M{
				"createAt": -1,
			},
		}
		filter = bson.M{} // 查询过滤器
	)
	// 设置分页参数
	opt.Limit, opt.Skip = Pagination(req.Page, req.Count)

	// 根据请求类型构建查询过滤器
	switch ApprovalOptionType(req.Type) {
	case ApprovalSubmit:
		// 查询我提交的：只查询申请人是当前用户的记录
		filter["userId"] = req.UserId
	case ApprovalAudit:
		// 查询待我审批的：只查询当前审批人是当前用户且状态为处理中的记录
		filter["approvalId"] = req.UserId
		filter["status"] = Processed // 只显示待处理的审批
	}

	// 执行查询
	err := entityList(ctx, m.col, filter, &data, opt)
	if err != nil {
		return nil, 0, err
	}

	// 获取总数
	count, err := m.col.CountDocuments(ctx, filter)
	if err != nil {
		return nil, 0, err
	}
	return data, count, nil
}

// Insert 插入一个新的审批记录
func (m *defaultApprovalModel) Insert(ctx context.Context, data *Approval) error {
	// 如果 ID 为空，则生成新的 ID 和时间戳
	if data.ID.IsZero() {
		data.ID = primitive.NewObjectID()
		data.CreateAt = time.Now().Unix()
		data.UpdateAt = time.Now().Unix()
	}

	_, err := m.col.InsertOne(ctx, data)
	return err
}

// FindOne 根据 ID 查找单个审批记录
func (m *defaultApprovalModel) FindOne(ctx context.Context, id string) (*Approval, error) {
	// 将字符串 ID 转换为 ObjectID
	oid, err := primitive.ObjectIDFromHex(id)
	if err != nil {
		return nil, ErrInvalidObjectId
	}

	var data Approval
	// 执行查询
	err = m.col.FindOne(ctx, bson.M{"_id": oid}).Decode(&data)
	switch err {
	case nil:
		return &data, nil
	case mongo.ErrNoDocuments:
		// 如果没有找到文档，返回自定义的 ErrNotFound 错误
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

// Update 更新一个已有的审批记录
func (m *defaultApprovalModel) Update(ctx context.Context, data *Approval) error {
	// 更新 UpdateAt 时间戳
	data.UpdateAt = time.Now().Unix()
	_, err := m.col.UpdateOne(ctx, bson.M{"_id": data.ID}, bson.M{"$set": data})
	return err
}

// Delete 根据 ID 删除一个审批记录
func (m *defaultApprovalModel) Delete(ctx context.Context, id string) error {
	// 将字符串 ID 转换为 ObjectID
	oid, err := primitive.ObjectIDFromHex(id)
	if err != nil {
		return ErrInvalidObjectId
	}
	_, err = m.col.DeleteOne(ctx, bson.M{"_id": oid})
	return err
}
