/**
 * @author: 公众号：IT杨秀才
 * @doc:后端，AI知识进阶，后端面试场景题大全：https://golangstar.cn/
 */
// Code generated by goctl. DO NOT EDIT.
package model

import (
	"context"
	"time"

	"go.mongodb.org/mongo-driver/bson"
	"go.mongodb.org/mongo-driver/bson/primitive"
	"go.mongodb.org/mongo-driver/mongo"
	"go.mongodb.org/mongo-driver/mongo/options"
)

type ChatLogModel interface {
	Insert(ctx context.Context, data *ChatLog) error
	FindOne(ctx context.Context, id string) (*ChatLog, error)
	Update(ctx context.Context, data *ChatLog) error
	Delete(ctx context.Context, id string) error
	ListBySendTime(ctx context.Context, cid string, sendStartTime, sendEndTime int64) ([]*ChatLog, error)
}

type defaultChatLogModel struct {
	col *mongo.Collection
}

func NewChatLogModel(db *mongo.Database) ChatLogModel {
	col := db.Collection("chat_log")
	return &defaultChatLogModel{
		col: col,
	}
}

func (m *defaultChatLogModel) Insert(ctx context.Context, data *ChatLog) error {
	if data.ID.IsZero() {
		data.ID = primitive.NewObjectID()
		data.CreateAt = time.Now().Unix()
		data.UpdateAt = time.Now().Unix()
	}

	_, err := m.col.InsertOne(ctx, data)
	return err
}

func (m *defaultChatLogModel) FindOne(ctx context.Context, id string) (*ChatLog, error) {
	oid, err := primitive.ObjectIDFromHex(id)
	if err != nil {
		return nil, ErrInvalidObjectId
	}

	var data ChatLog
	err = m.col.FindOne(ctx, bson.M{"_id": oid}).Decode(&data)
	switch err {
	case nil:
		return &data, nil
	case mongo.ErrNoDocuments:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultChatLogModel) Update(ctx context.Context, data *ChatLog) error {
	data.UpdateAt = time.Now().Unix()
	_, err := m.col.UpdateOne(ctx, bson.M{"_id": data.ID}, bson.M{"$set": data})
	return err
}

func (m *defaultChatLogModel) Delete(ctx context.Context, id string) error {
	oid, err := primitive.ObjectIDFromHex(id)
	if err != nil {
		return ErrInvalidObjectId
	}
	_, err = m.col.DeleteOne(ctx, bson.M{"_id": oid})
	return err
}

// ListBySendTime 根据会话ID和时间范围查询聊天记录
func (m *defaultChatLogModel) ListBySendTime(ctx context.Context, cid string, sendStartTime, sendEndTime int64) ([]*ChatLog, error) {
	var data []*ChatLog

	// 设置查询选项：按发送时间升序排列
	opt := &options.FindOptions{
		Sort: bson.M{
			"sendTime": 1,
		},
	}

	// 构建查询条件：根据会话ID查询
	filter := bson.M{
		"conversationId": cid,
	}

	// 如果指定了开始时间，添加大于等于条件
	if sendStartTime > 0 {
		filter["sendTime"] = bson.M{
			"$gte": sendStartTime,
		}
	}

	// 如果指定了结束时间，添加小于等于条件
	if sendEndTime > 0 {
		filter["sendTime"] = bson.M{
			"$lte": sendEndTime,
		}
	}

	// 执行查询并返回结果
	err := entityList(ctx, m.col, filter, &data, opt)

	return data, err
}
