/**
 * @author: 公众号：IT杨秀才
 * @doc:后端，AI知识进阶，后端面试场景题大全：https://golangstar.cn/
 */
// Code generated by goctl. DO NOT EDIT.
package model

import (
	"context"
	"AIWorkHelper/internal/domain"
	"time"

	"go.mongodb.org/mongo-driver/mongo/options"
	"go.mongodb.org/mongo-driver/bson"
	"go.mongodb.org/mongo-driver/bson/primitive"
	"go.mongodb.org/mongo-driver/mongo"
)

type DepartmentUserModel interface {
	Insert(ctx context.Context, data *DepartmentUser) error
	Inserts(ctx context.Context, depId string, uids []string) error
	AllToMap(ctx context.Context) (map[string]*DepartmentUser, error)
	List(ctx context.Context, req *domain.DepartmentListReq) ([]*DepartmentUser, error)
	FindOne(ctx context.Context, id string) (*DepartmentUser, error)
	FindByUserId(ctx context.Context, uid string) (*DepartmentUser, error)
	Update(ctx context.Context, data *DepartmentUser) error
	Delete(ctx context.Context, id string) error
	DeleteByDepId(ctx context.Context, id string) error
}

type defaultDepartmentUserModel struct {
	col *mongo.Collection
}

func NewDepartmentUserModel(db *mongo.Database) DepartmentUserModel {
	col := db.Collection("department_user")
	return &defaultDepartmentUserModel{
		col: col,
	}
}

func (m *defaultDepartmentUserModel) Insert(ctx context.Context, data *DepartmentUser) error {
	if data.ID.IsZero() {
		data.ID = primitive.NewObjectID()
		data.CreateAt = time.Now().Unix()
		data.UpdateAt = time.Now().Unix()
	}

	_, err := m.col.InsertOne(ctx, data)
	return err
}

// Inserts 批量插入部门用户关联
func (m *defaultDepartmentUserModel) Inserts(ctx context.Context, depId string, uids []string) error {
	data := make([]interface{}, 0, len(uids))
	now := time.Now().Unix()
	for _, uid := range uids { // 为每个用户ID创建关联记录
		data = append(data, &DepartmentUser{
			ID:       primitive.NewObjectID(),
			DepId:    depId,
			UserId:   uid,
			CreateAt: now,
			UpdateAt: now,
		})
	}
	_, err := m.col.InsertMany(ctx, data) // 批量插入到MongoDB
	return err
}

// AllToMap 查询所有部门用户关联并转换为Map结构
func (m *defaultDepartmentUserModel) AllToMap(ctx context.Context) (map[string]*DepartmentUser, error) {
	var (
		data []*DepartmentUser
		filter = bson.M{}
	)

	// 查询所有数据
	err := entityList(ctx, m.col, filter, &data)
	if err != nil {
		return nil,  err
	}

	res := make( map[string]*DepartmentUser)
	for i, _ := range data {
		res[data[i].DepId] = data[i] // 以部门ID为key构建Map
	}

	return res, nil
}

func (m *defaultDepartmentUserModel) List(ctx context.Context, req *domain.DepartmentListReq) ([]*DepartmentUser, error) {
	var (
		data []*DepartmentUser
		opt = &options.FindOptions{}
		filter = bson.M{}
	)

	if len(req.DepId) > 0 {
		filter["depId"] = req.DepId
	}

	// 查询到数据
	err := entityList(ctx, m.col, filter, &data,opt)
	if err != nil {
		return nil,  err
	}

	return data, nil
}

func (m *defaultDepartmentUserModel) FindOne(ctx context.Context, id string) (*DepartmentUser, error) {
	oid, err := primitive.ObjectIDFromHex(id)
	if err != nil {
		return nil, ErrInvalidObjectId
	}

	var data DepartmentUser
	err = m.col.FindOne(ctx, bson.M{"_id": oid}).Decode(&data)
	switch err {
	case nil:
		return &data, nil
	case mongo.ErrNoDocuments:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

// FindByUserId 根据用户ID查找部门用户关联（返回最新的记录）
func (m *defaultDepartmentUserModel) FindByUserId(ctx context.Context, uid string) (*DepartmentUser, error) {
	var data DepartmentUser
	// 按创建时间倒序排列，获取最新的记录
	opts := options.FindOne().SetSort(bson.D{{"createAt", -1}})
	err := m.col.FindOne(ctx, bson.M{"userId": uid}, opts).Decode(&data)
	switch err {
	case nil:
		return &data, nil
	case mongo.ErrNoDocuments:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

// Update 更新部门用户关联
func (m *defaultDepartmentUserModel) Update(ctx context.Context, data *DepartmentUser) error {
	data.UpdateAt = time.Now().Unix() // 更新时间戳
	_, err := m.col.UpdateOne(ctx, bson.M{"_id": data.ID}, bson.M{"$set": data})
	return err
}

// Delete 根据ID删除部门用户关联
func (m *defaultDepartmentUserModel) Delete(ctx context.Context, id string) error {
	oid, err := primitive.ObjectIDFromHex(id) // 转换为ObjectID
	if err != nil {
		return ErrInvalidObjectId
	}
	_, err = m.col.DeleteOne(ctx, bson.M{"_id": oid})
	return err
}

// DeleteByDepId 根据部门ID删除所有相关的用户关联
func (m *defaultDepartmentUserModel) DeleteByDepId(ctx context.Context, id string) error {
	_, err := m.col.DeleteMany(ctx, bson.M{"depId": id}) // 删除该部门的所有用户关联
	return err
}