/**
 * @author: 公众号：IT杨秀才
 * @doc:后端，AI知识进阶，后端面试场景题大全：https://golangstar.cn/
 */
// Code generated by goctl. DO NOT EDIT.
package model

import (
	"context"

	"go.mongodb.org/mongo-driver/bson"
	"go.mongodb.org/mongo-driver/bson/primitive"
	"go.mongodb.org/mongo-driver/mongo"
)

// TodoRecordModel 待办操作记录数据访问接口，定义了待办操作记录相关的所有数据库操作方法
type TodoRecordModel interface {
	Insert(ctx context.Context, data *TodoRecord) error   // 插入新待办操作记录
	FindOne(ctx context.Context, id string) (*TodoRecord, error) // 根据ID查找单个待办操作记录
	Update(ctx context.Context, data *TodoRecord) error   // 更新待办操作记录信息
	Delete(ctx context.Context, id string) error          // 删除待办操作记录
}

// defaultTodoRecordModel 待办操作记录数据访问的默认实现
type defaultTodoRecordModel struct {
	col *mongo.Collection // MongoDB集合引用
}

// NewTodoRecordModel 创建待办操作记录数据访问模型实例
func NewTodoRecordModel(db *mongo.Database) TodoRecordModel {
	col := db.Collection("todo_record") // 获取todo_record集合
	return &defaultTodoRecordModel{
		col: col,
	}
}

// Insert 插入新待办操作记录，注意：TodoRecord结构体没有ID字段，此方法可能需要调整
func (m *defaultTodoRecordModel) Insert(ctx context.Context, data *TodoRecord) error {
	// 注意：TodoRecord结构体中没有ID字段，这里的代码可能有问题
	// if data.ID.IsZero() {
	//     data.ID = primitive.NewObjectID()
	//     data.CreateAt = time.Now().Unix()
	//     data.UpdateAt = time.Now().Unix()
	// }

	_, err := m.col.InsertOne(ctx, data)
	return err
}

// FindOne 根据待办操作记录ID查找单个待办操作记录
func (m *defaultTodoRecordModel) FindOne(ctx context.Context, id string) (*TodoRecord, error) {
	oid, err := primitive.ObjectIDFromHex(id) // 将十六进制字符串转换为ObjectID
	if err != nil {
		return nil, ErrInvalidObjectId
	}

	var data TodoRecord
	err = m.col.FindOne(ctx, bson.M{"_id": oid}).Decode(&data)
	switch err {
	case nil:
		return &data, nil
	case mongo.ErrNoDocuments:
		return nil, ErrNotFound // 待办操作记录不存在
	default:
		return nil, err
	}
}

// Update 更新待办操作记录信息，注意：TodoRecord结构体没有ID和UpdateAt字段
func (m *defaultTodoRecordModel) Update(ctx context.Context, data *TodoRecord) error {
	// 注意：TodoRecord结构体中没有UpdateAt字段，这里的代码可能有问题
	// data.UpdateAt = time.Now().Unix()
	// _, err := m.col.UpdateOne(ctx, bson.M{"_id": data.ID}, bson.M{"$set": data})
	return nil // 暂时返回nil，需要根据实际结构体调整
}

// Delete 根据待办操作记录ID删除待办操作记录
func (m *defaultTodoRecordModel) Delete(ctx context.Context, id string) error {
	oid, err := primitive.ObjectIDFromHex(id) // 将十六进制字符串转换为ObjectID
	if err != nil {
		return ErrInvalidObjectId
	}
	_, err = m.col.DeleteOne(ctx, bson.M{"_id": oid})
	return err
}
