/**
 * @author: 公众号：IT杨秀才
 * @doc:后端，AI知识进阶，后端面试场景题大全：https://golangstar.cn/
 */
// Code generated by goctl. DO NOT EDIT.
package model

import (
	"AIWorkHelper/internal/domain"
	"context"
	"go.mongodb.org/mongo-driver/mongo/options"
	"time"

	"go.mongodb.org/mongo-driver/bson"
	"go.mongodb.org/mongo-driver/bson/primitive"
	"go.mongodb.org/mongo-driver/mongo"
)

// TodoModel 待办事项数据访问接口，定义了待办事项相关的所有数据库操作方法
type TodoModel interface {
	Insert(ctx context.Context, data *Todo) error                              // 插入新待办事项
	List(ctx context.Context, req *domain.TodoListReq) ([]*Todo, int64, error) // 分页查询待办事项列表
	FindOne(ctx context.Context, id string) (*Todo, error)                     // 根据ID查找单个待办事项
	Update(ctx context.Context, data *Todo) error                              // 更新待办事项信息
	UpdateFinished(ctx context.Context, data *Todo, isAllFinished bool) error  // 更新待办事项完成状态
	UpdateRecords(ctx context.Context, data *Todo) error                       // 更新待办事项记录
	Delete(ctx context.Context, id string) error                               // 删除待办事项
}

// defaultTodoModel 待办事项数据访问的默认实现
type defaultTodoModel struct {
	col *mongo.Collection // MongoDB集合引用
}

// NewTodoModel 创建待办事项数据访问模型实例
func NewTodoModel(db *mongo.Database) TodoModel {
	col := db.Collection("todo") // 获取todo集合
	return &defaultTodoModel{
		col: col,
	}
}

// Insert 插入新待办事项记录，如果ID为空会自动生成新的ObjectID和时间戳
func (m *defaultTodoModel) Insert(ctx context.Context, data *Todo) error {
	if data.ID.IsZero() { // 如果ID为空，自动生成新的ObjectID和时间戳
		data.ID = primitive.NewObjectID()
		data.CreateAt = time.Now().Unix()
		data.UpdateAt = time.Now().Unix()
	}

	_, err := m.col.InsertOne(ctx, data)
	return err
}

// FindOne 根据待办事项ID查找单个待办事项
func (m *defaultTodoModel) FindOne(ctx context.Context, id string) (*Todo, error) {
	oid, err := primitive.ObjectIDFromHex(id) // 将十六进制字符串转换为ObjectID
	if err != nil {
		return nil, ErrInvalidObjectId
	}

	var data Todo
	err = m.col.FindOne(ctx, bson.M{"_id": oid}).Decode(&data)
	switch err {
	case nil:
		return &data, nil
	case mongo.ErrNoDocuments:
		return nil, ErrNotFound // 待办事项不存在
	default:
		return nil, err
	}
}

// List 分页查询待办事项列表，支持按用户ID和时间范围过滤
func (m *defaultTodoModel) List(ctx context.Context, req *domain.TodoListReq) ([]*Todo, int64, error) {
	var (
		data   []*Todo
		opt    = &options.FindOptions{}
		filter = bson.M{}
	)
	opt.Limit, opt.Skip = Pagination(req.Page, req.Count) // 设置分页参数

	if len(req.UserId) > 0 { // 按用户ID过滤（查询该用户作为执行人的待办）
		filter["executes.userId"] = req.UserId
	}
	if req.StartTime > 0 { // 按开始时间过滤
		filter["create_at"] = bson.M{
			"$gte": req.StartTime,
		}
	}
	if req.EndTime > 0 { // 按结束时间过滤
		filter["create_at"] = bson.M{
			"$lte": req.EndTime,
		}
	}
	err := entityList(ctx, m.col, filter, &data, opt) // 查询待办事项数据
	if err != nil {
		return nil, 0, err
	}

	count, err := m.col.CountDocuments(ctx, filter) // 查询总数量
	if err != nil {
		return nil, 0, err
	}

	return data, count, nil
}

// Update 更新待办事项信息，会自动更新UpdateAt字段为当前时间戳
func (m *defaultTodoModel) Update(ctx context.Context, data *Todo) error {
	data.UpdateAt = time.Now().Unix() // 更新时间戳
	_, err := m.col.UpdateOne(ctx, bson.M{"_id": data.ID}, bson.M{"$set": data})
	return err
}

// UpdateFinished 更新待办事项完成状态，更新执行人状态，如果所有人完成则更新整体状态
func (m *defaultTodoModel) UpdateFinished(ctx context.Context, data *Todo, isAllFinished bool) error {
	update := bson.M{
		"executes":  data.Executes,     // 更新执行人状态
		"update_at": time.Now().Unix(), // 更新时间戳
	}

	if isAllFinished { // 如果所有执行人都完成，更新整体状态
		update["todo_status"] = TodoFinish
	}

	_, err := m.col.UpdateOne(ctx, bson.M{"_id": data.ID}, bson.M{"$set": update}) // 使用$set操作符
	return err
}

// UpdateRecords 更新待办事项的操作记录列表
func (m *defaultTodoModel) UpdateRecords(ctx context.Context, data *Todo) error {
	update := bson.M{
		"records":   data.Records,      // 更新记录列表
		"update_at": time.Now().Unix(), // 更新时间戳
	}
	_, err := m.col.UpdateOne(ctx, bson.M{"_id": data.ID}, bson.M{"$set": update}) // 使用$set操作符
	return err
}

// Delete 根据待办事项ID删除待办事项
func (m *defaultTodoModel) Delete(ctx context.Context, id string) error {
	oid, err := primitive.ObjectIDFromHex(id) // 将十六进制字符串转换为ObjectID
	if err != nil {
		return ErrInvalidObjectId
	}
	_, err = m.col.DeleteOne(ctx, bson.M{"_id": oid})
	return err
}
