/**
 * @author: 公众号：IT杨秀才
 * @doc:后端，AI知识进阶，后端面试场景题大全：https://golangstar.cn/
 */
// Code generated by goctl. DO NOT EDIT.
package model

import (
	"context"
	"time"

	"go.mongodb.org/mongo-driver/bson"
	"go.mongodb.org/mongo-driver/bson/primitive"
	"go.mongodb.org/mongo-driver/mongo"
)

// UserTodoModel 用户待办关联数据访问接口，定义了用户待办关联相关的所有数据库操作方法
type UserTodoModel interface {
	Insert(ctx context.Context, data *UserTodo) error                        // 插入新用户待办关联记录
	ListByTodoId(ctx context.Context, todoId string) ([]*UserTodo, error)    // 根据待办ID查询用户待办关联列表
	FindOne(ctx context.Context, id string) (*UserTodo, error)               // 根据ID查找单个用户待办关联
	Update(ctx context.Context, data *UserTodo) error                        // 更新用户待办关联信息
	Delete(ctx context.Context, id string) error                             // 删除用户待办关联
}

// defaultUserTodoModel 用户待办关联数据访问的默认实现
type defaultUserTodoModel struct {
	col *mongo.Collection // MongoDB集合引用
}

// NewUserTodoModel 创建用户待办关联数据访问模型实例
func NewUserTodoModel(db *mongo.Database) UserTodoModel {
	col := db.Collection("user_todo") // 获取user_todo集合
	return &defaultUserTodoModel{
		col: col,
	}
}

// Insert 插入新用户待办关联记录，如果ID为空会自动生成新的ObjectID和时间戳
func (m *defaultUserTodoModel) Insert(ctx context.Context, data *UserTodo) error {
	if data.ID.IsZero() {
		data.ID = primitive.NewObjectID()
		data.CreateAt = time.Now().Unix()
		data.UpdateAt = time.Now().Unix()
	}

	_, err := m.col.InsertOne(ctx, data)
	return err
}

// ListByTodoId 根据待办事项ID查询所有相关的用户待办关联记录
func (m *defaultUserTodoModel) ListByTodoId(ctx context.Context, todoId string) ([]*UserTodo, error) {
	var data []*UserTodo
	err := entityList(ctx, m.col, bson.M{"todo_id":todoId}, &data,nil) // 查询指定待办ID的所有用户关联记录
	if err != nil {
		return nil,  err
	}

	return data, err
}


// FindOne 根据用户待办关联ID查找单个用户待办关联
func (m *defaultUserTodoModel) FindOne(ctx context.Context, id string) (*UserTodo, error) {
	oid, err := primitive.ObjectIDFromHex(id)
	if err != nil {
		return nil, ErrInvalidObjectId
	}

	var data UserTodo
	err = m.col.FindOne(ctx, bson.M{"_id": oid}).Decode(&data)
	switch err {
	case nil:
		return &data, nil
	case mongo.ErrNoDocuments:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

// Update 更新用户待办关联信息，会自动更新UpdateAt字段为当前时间戳
func (m *defaultUserTodoModel) Update(ctx context.Context, data *UserTodo) error {
	data.UpdateAt = time.Now().Unix()
	_, err := m.col.UpdateOne(ctx, bson.M{"_id": data.ID}, bson.M{"$set": data})
	return err
}

// Delete 根据用户待办关联ID删除用户待办关联
func (m *defaultUserTodoModel) Delete(ctx context.Context, id string) error {
	oid, err := primitive.ObjectIDFromHex(id)
	if err != nil {
		return ErrInvalidObjectId
	}
	_, err = m.col.DeleteOne(ctx, bson.M{"_id": oid})
	return err
}
