/**
 * @author: 公众号：IT杨秀才
 * @doc:后端，AI知识进阶，后端面试场景题大全：https://golangstar.cn/
 */
// Code generated by goctl. DO NOT EDIT.
package model

import (
	"AIWorkHelper/internal/domain"
	"AIWorkHelper/pkg/xerr"
	"context"
	"go.mongodb.org/mongo-driver/mongo/options"
	"time"

	"go.mongodb.org/mongo-driver/bson"
	"go.mongodb.org/mongo-driver/bson/primitive"
	"go.mongodb.org/mongo-driver/mongo"
)

// UserModel 用户数据访问接口，定义了用户相关的所有数据库操作方法
type UserModel interface {
	Insert(ctx context.Context, data *User) error                                    // 插入新用户记录
	FindOne(ctx context.Context, id string) (*User, error)                          // 根据用户ID查找单个用户
	Update(ctx context.Context, data *User) error                                   // 更新用户信息
	Delete(ctx context.Context, id string) error                                    // 根据用户ID删除用户
	FindByName(ctx context.Context, name string) (*User, error)                     // 根据用户名查找用户
	FindAdminUser(ctx context.Context) (*User, error)                               // 查找管理员用户
	List(ctx context.Context, req *domain.UserListReq) ([]*User, int64, error)      // 分页查询用户列表，返回用户列表和总数
	ListToMaps(ctx context.Context, req *domain.UserListReq) (map[string]*User, error) // 查询用户列表并转换为以用户ID为key的map
}

// defaultUserModel 用户数据访问的默认实现
type defaultUserModel struct {
	col *mongo.Collection // MongoDB集合引用
}

// NewUserModel 创建用户数据访问模型实例
func NewUserModel(db *mongo.Database) UserModel {
	col := db.Collection("user") // 获取user集合
	return &defaultUserModel{
		col: col,
	}
}

// Insert 插入新用户记录到数据库，如果用户ID为空会自动生成新的ObjectID和时间戳
func (m *defaultUserModel) Insert(ctx context.Context, data *User) error {
	if data.ID.IsZero() { // 如果ID为空，自动生成新的ObjectID和时间戳
		data.ID = primitive.NewObjectID()
		data.CreateAt = time.Now().Unix()
		data.UpdateAt = time.Now().Unix()
	}

	_, err := m.col.InsertOne(ctx, data)
	return err
}

// FindOne 根据用户ID查找单个用户
func (m *defaultUserModel) FindOne(ctx context.Context, id string) (*User, error) {
	oid, err := primitive.ObjectIDFromHex(id) // 将十六进制字符串转换为ObjectID
	if err != nil {
		return nil, xerr.WithMessagef(ErrInvalidObjectId, "id: %v", id)
	}

	var data User
	err = m.col.FindOne(ctx, bson.M{"_id": oid}).Decode(&data)
	switch err {
	case nil:
		return &data, nil
	case mongo.ErrNoDocuments:
		return nil, ErrNotUser // 用户不存在
	default:
		return nil, err
	}
}

// FindByName 根据用户名查找用户
func (m *defaultUserModel) FindByName(ctx context.Context, name string) (*User, error) {
	var user User
	err := m.col.FindOne(ctx, bson.M{"name": name}).Decode(&user)
	switch err {
	case nil:
		return &user, nil
	case mongo.ErrNoDocuments:
		return nil, xerr.WithMessagef(ErrNotUser, "err %v ; name %v", ErrNotUser.Error(), name)
	default:
		return nil, err
	}
}

// FindAdminUser 查找管理员用户，查找isAdmin字段为true的用户
func (m *defaultUserModel) FindAdminUser(ctx context.Context) (*User, error) {
	var data User
	err := m.col.FindOne(ctx, bson.M{"isAdmin": true}).Decode(&data)
	switch err {
	case nil:
		return &data, nil
	case mongo.ErrNoDocuments:
		return nil, ErrNotUser // 管理员用户不存在
	default:
		return nil, err
	}
}

// Update 更新用户信息，会自动更新UpdateAt字段为当前时间戳
func (m *defaultUserModel) Update(ctx context.Context, data *User) error {
	data.UpdateAt = time.Now().Unix() // 更新时间戳
	_, err := m.col.UpdateOne(ctx, bson.M{"_id": data.ID}, bson.M{"$set": data})
	return err
}

// Delete 根据用户ID删除用户
func (m *defaultUserModel) Delete(ctx context.Context, id string) error {
	oid, err := primitive.ObjectIDFromHex(id) // 将十六进制字符串转换为ObjectID
	if err != nil {
		return ErrInvalidObjectId
	}
	_, err = m.col.DeleteOne(ctx, bson.M{"_id": oid})
	return err
}

// List 分页查询用户列表，支持按用户名和用户ID列表进行过滤查询
func (m *defaultUserModel) List(ctx context.Context, req *domain.UserListReq) ([]*User, int64, error) {
	var (
		data   []*User
		opt    = &options.FindOptions{}
		filter = bson.M{}
	)
	opt.Limit, opt.Skip = Pagination(req.Page, req.Count) // 设置分页参数

	if len(req.Name) > 0 { // 按用户名过滤
		filter["name"] = req.Name
	}

	if len(req.Ids) > 0 { // 按用户ID列表过滤
		oids := make([]primitive.ObjectID, 0, len(req.Ids))
		for _, id := range req.Ids {
			if len(id) == 0 {
				continue // 跳过空ID
			}
			oid, err := primitive.ObjectIDFromHex(id)
			if err != nil {
				return nil, 0, ErrInvalidObjectId
			}
			oids = append(oids, oid)
		}
		filter["_id"] = bson.M{
			"$in": oids, // 使用$in操作符查询多个ID
		}
	}

	err := entityList(ctx, m.col, filter, &data, opt) // 执行查询
	if err != nil {
		return nil, 0, err
	}

	count, err := m.col.CountDocuments(ctx, filter) // 统计符合条件的文档总数
	if err != nil {
		return nil, 0, err
	}

	return data, count, nil
}

// ListToMaps 查询用户列表并转换为以用户ID为key的map，便于根据用户ID快速查找用户信息
func (m *defaultUserModel) ListToMaps(ctx context.Context, req *domain.UserListReq) (map[string]*User, error) {
	datas, _, err := m.List(ctx, req)
	if err != nil {
		return nil, err
	}
	res := make(map[string]*User, len(datas)) // 创建以用户ID为key的map
	for i, data := range datas {
		res[data.ID.Hex()] = datas[i] // 使用ObjectID的十六进制字符串作为key
	}
	return res, nil
}
