// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2

package handler

import (
	"net/http"

	v1user "BackEnd/internal/handler/v1/user"
	"BackEnd/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/login",
				Handler: v1user.LoginHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/register",
				Handler: v1user.RegisterHandler(serverCtx),
			},
		},
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.Jwt},
			[]rest.Route{
				{
					Method:  http.MethodGet,
					Path:    "/info",
					Handler: v1user.InfoHandler(serverCtx),
				},
				{
					Method:  http.MethodPut,
					Path:    "/profile",
					Handler: v1user.UpdateProfileHandler(serverCtx),
				},
			}...,
		),
	)
}
