/**
 * @author: 公众号：IT杨秀才
 * @doc:后端，AI知识进阶，后端面试场景题大全：https://golangstar.cn/
 */
// Code generated by goctl. DO NOT EDIT.
package domain

type IdPathReq struct {
	Id string `uri:"id,omitempty"` // uri 标签表示从 URL 路径获取参数
}

type IdResp struct {
	Id string `json:"id,omitempty"` // json 标签表示 JSON 序列化字段名
}

type IdRespInfo struct {
	Code int     `json:"code"`
	Data *IdResp `json:"data"`
}

type User struct {
	Id       string `json:"id,omitempty"`       // 用户ID
	Password string `json:"password,omitempty"` // 密码
	Name     string `json:"name,omitempty"`     // 用户名
	Status   int    `json:"status,omitempty"`   // 状态：0=禁用 1=启用
}

type LoginReq struct {
	Name     string `json:"name,omitempty"`     // 用户名
	Password string `json:"password,omitempty"` // 密码
}

type LoginResp struct {
	Status       int    `json:"status,omitempty"`       // 状态：0=失败 1=成功
	Id           string `json:"id,omitempty"`           // 用户ID
	Name         string `json:"name,omitempty"`         // 用户名
	AccessToken  string `json:"token,omitempty"`        // JWT令牌
	AccessExpire int64  `json:"accessExpire,omitempty"` // 过期时间
	RefreshAfter int64  `json:"refreshAfter,omitempty"` // 刷新时间
}

type UserListReq struct {
	Ids   []string `json:"ids,omitempty"`   // 用户ID列表
	Name  string   `json:"name,omitempty"`  // 用户名模糊搜索
	Page  int      `json:"page,omitempty"`  // 页码
	Count int      `json:"count,omitempty"` // 每页数量
}

type UserListResp struct {
	Count int64   `json:"count"` // 总记录数
	List  []*User `json:"data"`  // 用户列表
}

type UpdatePasswordReq struct {
	Id     string `json:"id"`     // 用户ID
	OldPwd string `json:"oldPwd"` // 原密码
	NewPwd string `json:"newPwd"` // 新密码
}

// CreateGroupReq 创建群聊请求
// 对应前端: CreateGroupRequest
type CreateGroupReq struct {
	GroupId   string   `json:"groupId" binding:"required"`   // 群聊ID
	GroupName string   `json:"groupName" binding:"required"` // 群聊名称
	MemberIds []string `json:"memberIds" binding:"required"` // 群成员ID列表（不包括创建者）
}

// AddGroupMembersReq 添加群成员请求
type AddGroupMembersReq struct {
	GroupId   string   `json:"groupId" binding:"required"`   // 群聊ID
	MemberIds []string `json:"memberIds" binding:"required"` // 要添加的群成员ID列表
}

// GroupPathReq 群聊路径参数
type GroupPathReq struct {
	GroupId string `uri:"groupId" binding:"required"` // 群聊ID
	UserId  string `uri:"userId"`                     // 用户ID（可选）
}

type Department struct {
	Id         string            `json:"id, omitempty"`         // 部门ID
	Name       string            `json:"name, omitempty"`       // 部门名称
	ParentId   string            `json:"parentId, omitempty"`   // 父部门ID
	ParentPath string            `json:"parentPath, omitempty"` // 父部门路径
	Level      int               `json:"level, omitempty"`      // 部门层级
	LeaderId   string            `json:"leaderId, omitempty"`   // 部门负责人ID
	Leader     string            `json:"leader, omitempty"`     // 部门负责人姓名
	Count      int64             `json:"count, omitempty"`      // 部门人数
	Users      []*DepartmentUser `json:"users, omitempty"`      // 部门用户列表
	Child      []*Department     `json:"child, omitempty"`      // 子部门列表
}

type DepartmentUser struct {
	Id       string `json:"id,omitempty"`       // 关联ID
	UserId   string `json:"user,omitempty"`     // 用户ID
	DepId    string `json:"dep,omitempty"`      // 部门ID
	UserName string `json:"userName,omitempty"` // 用户姓名
}

type DepartmentListReq struct {
	DepId  string   `json:"depId,omitempty"`  // 单个部门ID
	DepIds []string `json:"depIds,omitempty"` // 多个部门ID列表
}

type DepartmentPathReq struct {
	DepId  string `path:"depId,omitempty"`  // 部门ID路径参数
	UserId string `path:"userId,omitempty"` // 用户ID路径参数
}

type SetDepartmentUser struct {
	DepId   string   `json:"depId"`   // 部门ID
	UserIds []string `json:"userIds"` // 用户ID列表
}

type AddDepartmentUser struct {
	DepId  string `json:"depId"`  // 部门ID
	UserId string `json:"userId"` // 要添加的用户ID
}

type RemoveDepartmentUser struct {
	DepId  string `json:"depId"`  // 部门ID
	UserId string `json:"userId"` // 要删除的用户ID
}

type DepartmentSoaResp struct {
	Id       string            `json:"id, omitempty"`       // 部门ID
	Name     string            `json:"name, omitempty"`     // 部门名称
	ParentId string            `json:"parentId, omitempty"` // 父部门ID
	Level    int               `json:"level, omitempty"`    // 部门层级
	LeaderId string            `json:"leaderId, omitempty"` // 负责人ID
	Leader   string            `json:"leader, omitempty"`   // 负责人姓名
	Count    int64             `json:"count, omitempty"`    // 部门人数
	Users    []*DepartmentUser `json:"users, omitempty"`    // 部门用户列表
	Child    []*Department     `json:"child, omitempty"`    // 子部门列表
}

type TodoRecord struct {
	TodoId   string `json:"todoId,omitempty"`
	UserId   string `json:"userId,omitempty"`
	UserName string `json:"userName,omitempty"`
	Content  string `json:"content,omitempty"`
	Image    string `json:"image,omitempty"`
	CreateAt int64  `json:"createAt,omitempty"`
}

type Todo struct {
	ID          string        `json:"id,omitempty"`
	CreatorId   string        `json:"creatorId,omitempty"`
	CreatorName string        `json:"creatorName,omitempty"`
	Title       string        `json:"title,omitempty"`
	DeadlineAt  int64         `json:"deadlineAt,omitempty"`
	Desc        string        `json:"desc,omitempty"`
	Status      int           `json:"status,omitempty"`
	Records     []*TodoRecord `json:"records,omitempty"`
	ExecuteIds  []string      `json:"executeIds,omitempty"` // 待办执行人
	TodoStatus  int           `json:"todoStatus,omitempty"`
}

type UserTodo struct {
	ID         string `json:"id,omitempty"`
	UserId     string `json:"userId,omitempty"`
	UserName   string `json:"userName,omitempty"`
	TodoId     string `json:"todoId,omitempty"`
	TodoStatus int    `json:"todoStatus,omitempty"` // 待办事项的状态
}

type TodoInfoResp struct {
	ID          string        `json:"id,omitempty"`
	CreatorId   string        `json:"creatorId,omitempty"`
	CreatorName string        `json:"creatorName,omitempty"`
	Title       string        `json:"title,omitempty"`
	DeadlineAt  int64         `json:"deadlineAt,omitempty"`
	Desc        string        `json:"desc,omitempty"`
	Records     []*TodoRecord `json:"records,omitempty"`
	ExecuteIds  []*UserTodo   `json:"executeIds,omitempty"`
	Status      int           `json:"status,omitempty"`
	TodoStatus  int           `json:"todoStatus,omitempty"`
}

type FinishedTodoReq struct {
	UserId string `json:"userId"`
	TodoId string `json:"todoId"`
}

type TodoListReq struct {
	Id        string `form:"id" json:"id,omitempty"`
	UserId    string `form:"userId" json:"userId,omitempty"`
	Page      int    `form:"page" json:"page,omitempty"`
	Count     int    `form:"count" json:"count,omitempty"`
	StartTime int64  `form:"startTime" json:"startTime,omitempty"`
	EndTime   int64  `form:"endTime" json:"endTime,omitempty"`
}

type TodoListResp struct {
	Count int64   `json:"count"`
	List  []*Todo `json:"data"`
}

type Approver struct {
	UserId   string `json:"userId"`
	UserName string `json:"userName"`
	Status   int    `json:"status"`
	Reason   string `json:"reason,omitempty"` //请假原由
}

type MakeCard struct {
	Date      int64  `json:"date,omitempty" mapstructure:"date,omitempty"`                   //补卡时间
	Reason    string `json:"reason,omitempty" mapstructure:"reason,omitempty"`               //补卡理由
	Day       int64  `json:"day,omitempty" mapstructure:"day,omitempty"`                     //补卡日期(20221011)
	CheckType int    `json:"workCheckType,omitempty" mapstructure:"workCheckType,omitempty"` //补卡类型
}

type Leave struct {
	Type      int     `json:"type,omitempty" mapstructure:"type,omitempty"`           //请假类型
	StartTime int64   `json:"startTime,omitempty" mapstructure:"startTime,omitempty"` //开始时间
	EndTime   int64   `json:"endTime,omitempty" mapstructure:"endTime,omitempty"`     //结束时间
	Duration  float32 `json:"duration,omitempty" mapstructure:"duration,omitempty"`   //时长
	Reason    string  `json:"reason,omitempty" mapstructure:"reason,omitempty"`       //请假原由
	TimeType  int     `json:"timeType,omitempty" mapstructure:"timeType,omitempty"`   //请假类型  1=小时 2=天
}

type GoOut struct {
	StartTime int64   `json:"startTime,omitempty" mapstructure:"omitempty"` //开始时间
	EndTime   int64   `json:"endTime,omitempty" mapstructure:"omitempty"`   //结束时间
	Duration  float32 `json:"duration,omitempty" mapstructure:"omitempty"`  //时长
	Reason    string  `json:"reason,omitempty" mapstructure:"omitempty"`    //请假原由
}

type Approval struct {
	Id          string    `json:"id,omitempty"`
	UserId      string    `json:"userId,omitempty"`
	No          string    `json:"no,omitempty"`
	Type        int       `json:"type,omitempty"`
	Status      int       `json:"status,omitempty"`
	Title       string    `json:"title,omitempty"`
	Abstract    string    `json:"abstract,omitempty"`
	Reason      string    `json:"reason,omitempty"`
	FinishAt    int64     `json:"finishAt,omitempty"`
	FinishDay   int64     `json:"finishDay,omitempty"`
	FinishMonth int64     `json:"finishMonth,omitempty"`
	FinishYeas  int64     `json:"finishYeas,omitempty"`
	MakeCard    *MakeCard `json:"makeCard,omitempty"`
	Leave       *Leave    `json:"leave,omitempty"`
	GoOut       *GoOut    `json:"goOut,omitempty"`
	UpdateAt    int64     `json:"updateAt,omitempty"`
	CreateAt    int64     `json:"createAt,omitempty"`
}

type ApprovalInfoResp struct {
	Id          string      `json:"id"`
	User        *Approver   `json:"user"`
	No          string      `json:"no"`
	Type        int         `json:"type"`
	Status      int         `json:"status"`
	Title       string      `json:"title"`
	Abstract    string      `json:"abstract"`
	Reason      string      `json:"reason"`
	Approver    *Approver   `json:"approver"`
	Approvers   []*Approver `json:"approvers"`
	CopyPersons []*Approver `json:"copyPersons"`
	FinishAt    int64       `json:"finishAt"`
	FinishDay   int64       `json:"finishDay"`
	FinishMonth int64       `json:"finishMonth"`
	FinishYeas  int64       `json:"finishYeas"`
	MakeCard    *MakeCard   `json:"makeCard"`
	Leave       *Leave      `json:"leave"`
	GoOut       *GoOut      `json:"goOut"`
	UpdateAt    int64       `json:"updateAt"`
	CreateAt    int64       `json:"createAt"`
}

type DisposeReq struct {
	Status     int
	Reason     string
	ApprovalId string
}

type ApprovalListReq struct {
	UserId string `form:"userId" json:"userId,omitempty"`
	Type   int    `form:"type" json:"type,omitempty"`
	Page   int    `form:"page" json:"page,omitempty"`
	Count  int    `form:"count" json:"count,omitempty"`
}

type ApprovalList struct {
	Id              string `json:"id"`
	No              string `json:"no"`
	Type            int    `json:"type"`
	Status          int    `json:"status"`
	Title           string `json:"title"`
	Abstract        string `json:"abstract"`
	CreateId        string `json:"createId"`
	ParticipatingId string `json:"participatingId"`
	CreateAt        int64  `json:"createAt"`
}

type ApprovalListResp struct {
	Count int64           `json:"count"`
	List  []*ApprovalList `json:"data"`
}

type ChatReq struct {
	Prompts    string `json:"prompts,omitempty"`
	ChatType   int    `json:"chatType,omitempty"`
	RelationId string `json:"relationId,omitempty"`
	StartTime  int64  `json:"startTime,omitempty"`
	EndTime    int64  `json:"endTime,omitempty"`
}

type ChatResp struct {
	ChatType int         `json:"chatType,omitempty"`
	Data     interface{} `json:"data"`
}

type FileResp struct {
	Host     string `json:"host"`     // 文件访问主机地址
	File     string `json:"file"`     // 文件相对路径
	Filename string `json:"filename"` // 文件名称
}

type FileListResp struct {
	List []*FileResp `json:"list"` // 文件列表
}
